entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

http:
  routers:
    http-catchall:
      rule: HostRegexp(`{host:.+}`)
      entrypoints:
        - web
      middlewares:
        - redirect-to-https

  middlewares:  
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsEncrypt:
    acme:
      email: "gomihagle@gmail.com"
      storage: letsencrypt/acme.json
      httpChallenge:
        entrypoint: web

api:
  dashboard: true
  debug: true